version: "3.7"
services:
  simulator-server:
    image: simulator-server
    container_name: simulator-server
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://simulator-etcd:2379
      - CORS_ALLOWED_ORIGIN_LIST=http://localhost:3000
      - KUBE_API_HOST=0.0.0.0
      - KUBE_API_PORT=3131
    ports:
      - "1212:1212"
      - "3131:3131"
    restart: always
    tty: true
    networks:
      - simulator-internal-network
  simulator-frontend:
    image: simulator-frontend
    restart: always
    container_name: simulator-frontend
    environment:
      - HOST=0.0.0.0
      - BASE_URL=http://localhost:1212
      - KUBE_API_SERVER_URL=http://localhost:3131
    ports:
    - "3000:3000"
    tty: true
  simulator-etcd:
    image: quay.io/coreos/etcd:v3.4.0
    container_name: simulator-etcd
    restart: always
    volumes:
      - simulator-etcd-data:/var/lib/etcd
    command: etcd --advertise-client-urls http://simulator-etcd:2379 --data-dir /var/lib/etcd --listen-client-urls http://0.0.0.0:2379 --initial-cluster-state new --initial-cluster-token tkn
    networks:
      - simulator-internal-network
  firmament: 
    command: [/firmament/build/src/firmament_scheduler, --flagfile=/firmament/config/firmament_scheduler_cpu_mem.cfg]
    image: huaweifirmament/firmament:latest
    restart: always
    container_name: firmament-service.kube-system
    ports:
      - "9090:9090"
    networks:
      - simulator-internal-network   
  poseidon:
    depends_on:
        - firmament
    command: [/poseidon, --logtostderr, --kubeConfig=/config/kubeconfig.cfg, --kubeVersion=1.6]
    volumes:
      - ./kubeconfig/:/config/
    image: huaweiposeidon/poseidon:latest
    restart: always
    container_name: poseidon
    networks:
      - simulator-internal-network
    environment:
      - KUBERNETES_SERVICE_HOST=localhost
      - KUBERNETES_SERVICE_PORT=3131

volumes:
  simulator-etcd-data:
networks:
  simulator-internal-network:
    driver: bridge
